import { useEffect, useMemo, useRef, useState } from "react";
import { RUN_DATA } from "./runData";

// Real HSEvo run on the BPP online problem (lower objective is better).
// Each individual is [iteration, objective]. In HSEvo's loop every iteration
// is a single operator stage, so we can attribute each individual to the
// operator that produced it:
//   iter 1            -> initialization
//   iter % 3 === 2    -> crossover      (2, 5, 8, ...)
//   iter % 3 === 0    -> elitist mutation (3, 6, 9, ...)
//   iter % 3 === 1 >1 -> harmony search (4, 7, 10, ...)

const MAX_ITER = Math.max(...RUN_DATA.map(([i]) => i));

type OpKey = "init" | "crossover" | "mutation" | "hs";

const OP: Record<
  OpKey,
  { label: string; dot: string; stroke: string; swatch: string; border: string }
> = {
  init: {
    label: "Initialization",
    dot: "fill-zinc-400/70 dark:fill-zinc-500/70",
    stroke: "stroke-zinc-400 dark:stroke-zinc-500",
    swatch: "bg-zinc-400",
    border: "border-zinc-400 dark:border-zinc-500",
  },
  crossover: {
    label: "Crossover",
    dot: "fill-teal-500/70 dark:fill-teal-400/70",
    stroke: "stroke-teal-500 dark:stroke-teal-400",
    swatch: "bg-teal-500",
    border: "border-teal-500 dark:border-teal-400",
  },
  mutation: {
    label: "Elitist mutation",
    dot: "fill-amber-500/80 dark:fill-amber-400/80",
    stroke: "stroke-amber-500 dark:stroke-amber-400",
    swatch: "bg-amber-500",
    border: "border-amber-500 dark:border-amber-400",
  },
  hs: {
    label: "Harmony search",
    dot: "fill-violet-500/70 dark:fill-violet-400/70",
    stroke: "stroke-violet-500 dark:stroke-violet-400",
    swatch: "bg-violet-500",
    border: "border-violet-500 dark:border-violet-400",
  },
};

const opOf = (iter: number): OpKey => {
  if (iter === 1) return "init";
  const m = iter % 3;
  if (m === 2) return "crossover";
  if (m === 0) return "mutation";
  return "hs";
};

// Selection is a phase (it produces no individuals) that starts each round,
// right before a crossover iteration. We render it on the transition arrows so
// it is separated from the harmony search operator.
const SELECTION = {
  label: "Selection",
  stroke: "stroke-rose-500 dark:stroke-rose-400",
  swatch: "bg-rose-500",
  border: "border-rose-500 dark:border-rose-400",
};

// The HSEvo pipeline steps, shown beside the chart and highlighted in sync with
// the current operator. `phase` links a step to the operator iteration during
// which it is active ("selection" steps are active during crossover rounds,
// "always" steps run every iteration).
type Phase = OpKey | "selection" | "always";

type Detail = { type: "code" | "text"; content: string };

type StepDef = {
  title: string;
  description: string;
  phase: Phase;
  input?: Detail;
  output?: Detail;
};

// Input/output examples use the BPP online problem of this run (design a
// `priority(item, bins_remain_cap)` heuristic; lower objective is better).
const STEPS: StepDef[] = [
  {
    title: "Individual encoding",
    description:
      "Each heuristic is a Python code snippet generated by the LLM, so individuals are not tied to any fixed format and can be evaluated directly on the problem.",
    phase: "init",
    input: {
      type: "text",
      content:
        "Raw LLM response containing reasoning plus a fenced Python code block.",
    },
    output: {
      type: "code",
      content: `def priority_v2(item: float, bins_remain_cap: np.ndarray) -> np.ndarray:
    # parsed from the LLM response and stored as the individual
    ratios = item / bins_remain_cap
    return -np.log(ratios)`,
    },
  },
  {
    title: "Initialization",
    description:
      "The generator LLM is prompted with the task and a seed function to produce an initial population of diverse candidate heuristics.",
    phase: "init",
    input: {
      type: "text",
      content: `System: You are an expert designing bin-packing heuristics.
User: Write a priority(item, bins_remain_cap) function that returns a
priority score per bin. The bin with the highest score gets the item.
Seed function:
def priority_v1(item, bins_remain_cap):
    ratios = item / bins_remain_cap
    return -np.log(ratios)`,
    },
    output: {
      type: "text",
      content:
        "An initial population of 20 candidate priority(...) heuristics (diverse scoring strategies).",
    },
  },
  {
    title: "Selection",
    description:
      "Parent heuristics are sampled from the current population to be recombined into new offspring.",
    phase: "selection",
    input: {
      type: "text",
      content:
        "Current population with objective scores, e.g. [3.95, 3.99, 4.02, 4.09, ...] (lower is better).",
    },
    output: {
      type: "text",
      content:
        "Parent pairs for crossover, e.g. (obj 3.95, obj 3.99) and (obj 4.02, obj 4.09).",
    },
  },
  {
    title: "Flash reflection",
    description:
      "A cost-efficient two-step reflection: analyze the ranked population, then compare against the previous analysis to produce guide information for later stages.",
    phase: "crossover",
    input: {
      type: "text",
      content:
        "Ranked list of heuristics (best to worst) with their code.",
    },
    output: {
      type: "text",
      content: `Keywords: item-size ratio, remaining capacity
Advice: favour bins with the tightest fit
Avoid: purely first-fit placement
Explanation: tighter fits leave more usable space`,
    },
  },
  {
    title: "Crossover",
    description:
      "Offspring heuristics blend the strengths of two parents, steered by the guide information from flash reflection.",
    phase: "crossover",
    input: {
      type: "text",
      content:
        "Two parent heuristics + the flash-reflection guide information.",
    },
    output: {
      type: "code",
      content: `def priority_v2(item, bins_remain_cap):
    # offspring: blend tight-fit ratio with leftover-space penalty
    fit = item / bins_remain_cap
    leftover = bins_remain_cap - item
    return -np.log(fit) - 0.3 * leftover`,
    },
  },
  {
    title: "Elitist mutation",
    description:
      "The best-performing (elite) heuristic is mutated using insights from flash reflection to push toward better variants.",
    phase: "mutation",
    input: {
      type: "text",
      content:
        "The current elite (best) heuristic + comprehensive reflection hints.",
    },
    output: {
      type: "code",
      content: `def priority_v2(item, bins_remain_cap):
    # mutated: add a sharper penalty for near-overflow bins
    fit = item / bins_remain_cap
    penalty = np.where(bins_remain_cap - item < 0.1, 5.0, 0.0)
    return -np.log(fit) - penalty`,
    },
  },
  {
    title: "Harmony search tuning",
    description:
      "A harmony search process tunes the numeric parameters of a heuristic to balance diversity and convergence and avoid premature convergence.",
    phase: "hs",
    input: {
      type: "code",
      content: `# extracted tunable parameters + ranges
parameter_ranges = {
    "leftover_weight": (0.0, 1.0),
    "overflow_penalty": (1.0, 10.0),
}
# HM size = 5, HMCR = 0.7, PAR = 0.5, bandwidth = 0.2, max iters = 5`,
    },
    output: {
      type: "code",
      content: `# best harmony found (tuned parameters)
leftover_weight = 0.42
overflow_penalty = 6.3
# -> new individual added to the population`,
    },
  },
  {
    title: "Evaluation",
    description:
      "Every heuristic is run on the problem to obtain its objective score, and the population is updated for the next iteration.",
    phase: "always",
    input: {
      type: "text",
      content: "A candidate priority(...) heuristic run on the BPP instances.",
    },
    output: {
      type: "text",
      content: "current best objective: 1.7301382121905118",
    },
  },
];

const isStepActive = (phase: Phase, op: OpKey): boolean => {
  if (phase === "always") return true;
  if (phase === "selection") return op === "crossover";
  return phase === op;
};

const phaseBorder = (phase: Phase): string => {
  if (phase === "always") return "border-blue-500 dark:border-blue-400";
  if (phase === "selection") return SELECTION.border;
  return OP[phase].border;
};

type Individual = { obj: number; xJitter: number };

// Group individuals by iteration and give each a deterministic horizontal
// offset so points in the same iteration spread out instead of overlapping.
const ITERS: Individual[][] = (() => {
  const byIter: number[][] = Array.from({ length: MAX_ITER + 1 }, () => []);
  for (const [i, o] of RUN_DATA) byIter[i].push(o);
  return byIter.map((objs) => {
    const n = objs.length;
    return objs.map((obj, k) => ({
      obj,
      xJitter: n > 1 ? (k / (n - 1) - 0.5) * 0.6 : 0,
    }));
  });
})();

const BEST_SO_FAR: number[] = (() => {
  const out: number[] = [];
  let best = Infinity;
  for (let i = 1; i <= MAX_ITER; i++) {
    for (const ind of ITERS[i]) best = Math.min(best, ind.obj);
    out[i] = best;
  }
  return out;
})();

const TOTAL_BY_ITER: number[] = (() => {
  const out: number[] = [];
  let sum = 0;
  for (let i = 1; i <= MAX_ITER; i++) {
    sum += ITERS[i].length;
    out[i] = sum;
  }
  return out;
})();

// y-axis focuses on the bulk of the data; worse (higher) individuals are
// clamped to the top edge so a few bad heuristics don't flatten the view.
const Y_MIN = 1.5;
const Y_MAX = 6;

export function RunProgress() {
  const [iter, setIter] = useState(1);
  const [playing, setPlaying] = useState(true);
  const [modalStep, setModalStep] = useState<StepDef | null>(null);
  const timer = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => {
    if (!modalStep) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") setModalStep(null);
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [modalStep]);

  useEffect(() => {
    if (!playing) return;
    timer.current = setInterval(() => {
      setIter((i) => {
        if (i >= MAX_ITER) {
          setPlaying(false);
          return i;
        }
        return i + 1;
      });
    }, 500);
    return () => {
      if (timer.current) clearInterval(timer.current);
    };
  }, [playing]);

  const done = iter >= MAX_ITER;
  const bestObjective = BEST_SO_FAR[iter];
  const evaluated = TOTAL_BY_ITER[iter];
  const opKey = opOf(iter);
  const currentOp = OP[opKey];

  // Chart geometry
  const width = 820;
  const height = 372;
  const padL = 52;
  const padR = 16;
  const padT = 20;
  const padB = 74;
  const plotW = width - padL - padR;
  const plotH = height - padT - padB;
  const baseline = height - padB;

  const xForIter = (i: number) => padL + (i / (MAX_ITER + 1)) * plotW;
  const yForObj = (o: number) => {
    const clamped = Math.min(Math.max(o, Y_MIN), Y_MAX);
    return padT + ((Y_MAX - clamped) / (Y_MAX - Y_MIN)) * plotH;
  };
  const iterBand = plotW / (MAX_ITER + 1);

  const { dots, bestLine } = useMemo(() => {
    const dots: { x: number; y: number; op: OpKey; clamped: boolean }[] = [];
    for (let i = 1; i <= iter; i++) {
      const op = opOf(i);
      for (const ind of ITERS[i]) {
        dots.push({
          x: xForIter(i + ind.xJitter),
          y: yForObj(ind.obj),
          op,
          clamped: ind.obj > Y_MAX,
        });
      }
    }
    const bestLine: string = Array.from({ length: iter }, (_, k) => {
      const i = k + 1;
      return `${xForIter(i)},${yForObj(BEST_SO_FAR[i])}`;
    }).join(" ");
    return { dots, bestLine };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [iter]);

  const yTicks: number[] = [];
  for (let v = Y_MAX; v >= Y_MIN - 1e-9; v -= 0.5) yTicks.push(Number(v.toFixed(1)));
  const iterList = Array.from({ length: MAX_ITER }, (_, k) => k + 1);

  const restart = () => {
    setIter(1);
    setPlaying(true);
  };

  return (
    <div className="not-prose overflow-hidden rounded-xl border border-zinc-200 bg-white shadow-sm dark:border-zinc-700 dark:bg-zinc-900">
      <div className="flex flex-wrap items-center gap-x-8 gap-y-2 border-b border-zinc-200 p-4 dark:border-zinc-700">
        <span
          className={`inline-flex items-center gap-2 rounded-full px-3 py-1 text-sm font-medium ${
            done
              ? "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/50 dark:text-emerald-300"
              : "bg-blue-100 text-blue-700 dark:bg-blue-900/50 dark:text-blue-300"
          }`}
        >
          <span
            className={`h-2 w-2 rounded-full ${
              done ? "bg-emerald-500" : "animate-pulse bg-blue-500"
            }`}
          />
          {done ? "Finished" : "Evolving"}
        </span>
        <div>
          <div className="text-xs tracking-wide text-zinc-500 uppercase dark:text-zinc-400">
            Iteration
          </div>
          <div className="font-mono text-lg font-semibold text-zinc-900 tabular-nums dark:text-zinc-100">
            {iter} / {MAX_ITER}
          </div>
        </div>
        <div>
          <div className="text-xs tracking-wide text-zinc-500 uppercase dark:text-zinc-400">
            Operator
          </div>
          <div className="flex items-center gap-2 text-lg font-semibold text-zinc-900 dark:text-zinc-100">
            <span className={`h-3 w-3 rounded-full ${currentOp.swatch}`} />
            {currentOp.label}
          </div>
        </div>
        <div>
          <div className="text-xs tracking-wide text-zinc-500 uppercase dark:text-zinc-400">
            Individuals evaluated
          </div>
          <div className="font-mono text-lg font-semibold text-zinc-900 tabular-nums dark:text-zinc-100">
            {evaluated}
          </div>
        </div>
        <div>
          <div className="text-xs tracking-wide text-zinc-500 uppercase dark:text-zinc-400">
            Current best objective
          </div>
          <div className="font-mono text-lg font-semibold text-blue-600 tabular-nums dark:text-blue-400">
            {bestObjective.toFixed(4)}
          </div>
        </div>
      </div>

      <div className="grid gap-5 p-4 lg:grid-cols-[1.7fr_1fr]">
        <div className="min-w-0">
        <svg
          viewBox={`0 0 ${width} ${height}`}
          className="h-auto w-full"
          role="img"
          aria-label="All individuals coloured by operator and best objective across iterations"
        >
          {/* y gridlines */}
          {yTicks.map((t) => (
            <g key={`y${t}`}>
              <line
                x1={padL}
                x2={width - padR}
                y1={yForObj(t)}
                y2={yForObj(t)}
                className="stroke-zinc-200 dark:stroke-zinc-700"
                strokeWidth={1}
              />
              <text
                x={padL - 8}
                y={yForObj(t) + 4}
                textAnchor="end"
                className="fill-zinc-500 dark:fill-zinc-400"
                fontSize={11}
              >
                {t.toFixed(1)}
              </text>
            </g>
          ))}

          <text
            x={14}
            y={padT + plotH / 2}
            textAnchor="middle"
            className="fill-zinc-600 dark:fill-zinc-300"
            fontSize={12}
            transform={`rotate(-90 14 ${padT + plotH / 2})`}
          >
            Objective (lower is better)
          </text>

          {/* All individuals, coloured by operator */}
          {dots.map((d, i) => (
            <circle
              key={i}
              cx={d.x}
              cy={d.y}
              r={2.7}
              className={OP[d.op].dot}
            />
          ))}

          {/* Best-so-far objective line */}
          {iter > 1 && (
            <polyline
              points={bestLine}
              fill="none"
              className="stroke-blue-600 dark:stroke-blue-400"
              strokeWidth={2.5}
            />
          )}
          <circle
            cx={xForIter(iter)}
            cy={yForObj(bestObjective)}
            r={5}
            className="fill-blue-600 dark:fill-blue-400"
          />

          {/* X-axis baseline */}
          <line
            x1={xForIter(1) - iterBand / 2}
            x2={xForIter(MAX_ITER) + iterBand / 2}
            y1={baseline}
            y2={baseline}
            className="stroke-zinc-300 dark:stroke-zinc-600"
            strokeWidth={1}
          />
          {/* Only the selection transition (into each crossover iteration) is
              highlighted on the axis; other transitions use the plain baseline. */}
          {iterList
            .slice(0, -1)
            .filter((i) => opOf(i + 1) === "crossover")
            .map((i) => (
              <line
                key={`op${i}`}
                x1={xForIter(i)}
                x2={xForIter(i + 1)}
                y1={baseline}
                y2={baseline}
                className={SELECTION.stroke}
                strokeWidth={3}
              />
            ))}
          {/* Iteration ticks (coloured by operator) and numbers */}
          {iterList.map((i) => (
            <g key={`t${i}`}>
              <line
                x1={xForIter(i)}
                x2={xForIter(i)}
                y1={baseline}
                y2={baseline + 5}
                className={OP[opOf(i)].stroke}
                strokeWidth={2}
              />
              <text
                x={xForIter(i)}
                y={baseline + 17}
                textAnchor="middle"
                fontSize={9}
                className="fill-zinc-500 dark:fill-zinc-400"
              >
                {i}
              </text>
            </g>
          ))}
          <text
            x={padL + plotW / 2}
            y={height - 6}
            textAnchor="middle"
            className="fill-zinc-600 dark:fill-zinc-300"
            fontSize={12}
          >
            Iteration (one operator per iteration)
          </text>
        </svg>

        <div className="mt-2 flex flex-wrap items-center justify-center gap-x-5 gap-y-1 text-xs text-zinc-500 dark:text-zinc-400">
          <span className="inline-flex items-center gap-1.5">
            <span className={`h-2.5 w-2.5 rounded-full ${OP.init.swatch}`} />
            {OP.init.label}
          </span>
          <span className="inline-flex items-center gap-1.5">
            <span className={`h-2 w-4 rounded-full ${SELECTION.swatch}`} /> {SELECTION.label} (starts each round)
          </span>
          <span className="inline-flex items-center gap-1.5">
            <span className={`h-2.5 w-2.5 rounded-full ${OP.crossover.swatch}`} />
            {OP.crossover.label}
          </span>
          <span className="inline-flex items-center gap-1.5">
            <span className={`h-2.5 w-2.5 rounded-full ${OP.mutation.swatch}`} />
            {OP.mutation.label}
          </span>
          <span className="inline-flex items-center gap-1.5">
            <span className={`h-2.5 w-2.5 rounded-full ${OP.hs.swatch}`} />
            {OP.hs.label}
          </span>
          <span className="inline-flex items-center gap-1.5">
            <span className="h-1 w-4 rounded-full bg-blue-600" /> best objective so far
          </span>
        </div>

        <div className="mt-3 flex items-center justify-center gap-3">
          <button
            type="button"
            onClick={() => {
              setPlaying(false);
              setIter((i) => Math.max(1, i - 1));
            }}
            disabled={iter <= 1}
            className="rounded-full border border-zinc-300 px-3 py-1.5 text-sm font-medium text-zinc-700 hover:bg-zinc-100 disabled:cursor-not-allowed disabled:opacity-40 dark:border-zinc-600 dark:text-zinc-200 dark:hover:bg-zinc-800"
            aria-label="Previous iteration"
          >
            ‹ Prev
          </button>
          <button
            type="button"
            onClick={() => (done ? restart() : setPlaying((p) => !p))}
            className="rounded-full bg-zinc-800 px-4 py-1.5 text-sm font-medium text-white hover:bg-black dark:bg-zinc-200 dark:text-zinc-900 dark:hover:bg-white"
          >
            {done ? "Replay" : playing ? "Pause" : "Play"}
          </button>
          <button
            type="button"
            onClick={() => {
              setPlaying(false);
              setIter((i) => Math.min(MAX_ITER, i + 1));
            }}
            disabled={iter >= MAX_ITER}
            className="rounded-full border border-zinc-300 px-3 py-1.5 text-sm font-medium text-zinc-700 hover:bg-zinc-100 disabled:cursor-not-allowed disabled:opacity-40 dark:border-zinc-600 dark:text-zinc-200 dark:hover:bg-zinc-800"
            aria-label="Next iteration"
          >
            Next ›
          </button>
          <input
            type="range"
            min={1}
            max={MAX_ITER}
            value={iter}
            onChange={(e) => {
              setPlaying(false);
              setIter(Number(e.target.value));
            }}
            className="w-40 accent-blue-500"
            aria-label="Scrub through iterations"
          />
        </div>
        </div>

        <div className="min-w-0">
          <div className="mb-2 text-xs font-medium tracking-wide text-zinc-500 uppercase dark:text-zinc-400">
            HSEvo pipeline
          </div>
          <ol className="m-0 flex list-none flex-col gap-1.5 p-0">
            {STEPS.map((s, idx) => {
              const active = isStepActive(s.phase, opKey);
              return (
                <li
                  key={s.title}
                  className={`rounded-md border-l-4 py-1.5 pr-2 pl-3 transition-colors ${
                    active
                      ? `${phaseBorder(s.phase)} bg-zinc-50 dark:bg-zinc-800/60`
                      : "border-transparent opacity-55"
                  }`}
                >
                  <div className="flex items-baseline gap-2">
                    <span className="font-mono text-xs text-zinc-400">
                      {idx + 1}
                    </span>
                    <span className="text-sm font-semibold text-zinc-900 dark:text-zinc-100">
                      {s.title}
                    </span>
                  </div>
                  {active && (
                    <p className="mt-1 mb-0 text-xs leading-relaxed text-zinc-600 dark:text-zinc-300">
                      {s.description}
                    </p>
                  )}
                  {active && (s.input || s.output) && (
                    <div className="mt-1.5">
                      <button
                        type="button"
                        onClick={() => setModalStep(s)}
                        className="inline-flex items-center gap-1 rounded-full border border-blue-300 bg-blue-50 px-2 py-0.5 text-[10px] font-medium text-blue-700 hover:bg-blue-100 dark:border-blue-800 dark:bg-blue-950/40 dark:text-blue-300 dark:hover:bg-blue-900/40"
                      >
                        Input / Output
                      </button>
                    </div>
                  )}
                </li>
              );
            })}
          </ol>
        </div>
      </div>

      {modalStep && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"
          onClick={() => setModalStep(null)}
          role="dialog"
          aria-modal="true"
        >
          <div
            className="max-h-[85vh] w-full max-w-2xl overflow-auto rounded-xl bg-white p-5 shadow-xl dark:bg-zinc-900"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="mb-3 flex items-start justify-between gap-4">
              <h3 className="m-0 text-lg font-semibold text-zinc-900 dark:text-zinc-100">
                {modalStep.title}
              </h3>
              <button
                type="button"
                onClick={() => setModalStep(null)}
                className="rounded-full px-2 text-2xl leading-none text-zinc-500 hover:bg-zinc-100 hover:text-zinc-900 dark:hover:bg-zinc-800 dark:hover:text-zinc-100"
                aria-label="Close"
              >
                ×
              </button>
            </div>
            <p className="mt-0 mb-4 text-sm text-zinc-600 dark:text-zinc-300">
              {modalStep.description}
            </p>
            {modalStep.input && <DetailBlock label="Input" detail={modalStep.input} />}
            {modalStep.output && (
              <div className="mt-4">
                <DetailBlock label="Output" detail={modalStep.output} />
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

function DetailBlock({ label, detail }: { label: string; detail: Detail }) {
  return (
    <div className="overflow-hidden rounded-lg border border-zinc-200 dark:border-zinc-700">
      <div className="border-b border-zinc-200 bg-zinc-100 px-3 py-1.5 text-xs font-semibold tracking-wide text-zinc-600 uppercase dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-300">
        {label}
      </div>
      {detail.type === "code" ? (
        <pre className="m-0 overflow-x-auto bg-zinc-50 px-3 py-2 text-xs leading-relaxed text-zinc-800 dark:bg-zinc-950 dark:text-zinc-200">
          <code>{detail.content}</code>
        </pre>
      ) : (
        <p className="m-0 px-3 py-2 text-sm whitespace-pre-wrap text-zinc-700 dark:text-zinc-300">
          {detail.content}
        </p>
      )}
    </div>
  );
}
